on:
  issue_comment:
    types: [created]

jobs:
  fast_forward_merge_job:
    name: Fast Forward Merge
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
    runs-on: ubuntu-latest
    steps:
      - name: Fast Forward PR
        uses: endre-spotlab/fast-forward-js-action@2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
