on:
  issue_comment:
    types: [created]

jobs:
  fast_forward_merge_job:
    name: Fast Forward Merge
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          repository: "summera/fast-forward-js-action"
          ref: "574cde71b05e0ed76ece02e8122bab18f29a13e0"
      - name: Fast Forward PR
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
