on:
  issue_comment:
    types: [created]

jobs:
  fast_forward_merge_job:
    name: Fast Forward Merge
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
    runs-on: ubuntu-latest
    steps:
      - name: Fast Forward PR
        uses: summera/fast-forward-js-action@574cde71b05e0ed76ece02e8122bab18f29a13e0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
